# Generated by Django 5.0 on 2023-12-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCareSpecialist',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_price', models.CharField(max_length=5)),
                ('adult_price', models.CharField(max_length=15)),
                ('child_price', models.CharField(max_length=9)),
                ('num_per_day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipatesIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_per_day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueTypes',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('revenue_type', models.CharField(max_length=20)),
                ('revenue_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VeterinarianCaresFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ZooAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_price', models.CharField(max_length=10)),
                ('adult_price', models.CharField(max_length=15)),
                ('child_price', models.CharField(max_length=9)),
                ('revenue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoo_admissions', to='myapp.revenuetypes')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='building',
            name='square_footage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='monthly_food_cost',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='population',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_status',
            field=models.CharField(default='Healthy', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.building'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default='Restroom', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='Facility', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='address_state',
            field=models.CharField(default='NJ', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Newark', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='First', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate_id',
            field=models.CharField(default='H4', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.CharField(default='Staff', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Last', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='minit',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(default='123 Maple St', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor_id',
            field=models.CharField(default='54321', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='zip',
            field=models.IntegerField(default='54321'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='food_cost',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='species_name',
            field=models.CharField(default='Tiger', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth_year',
            field=models.CharField(default='2014', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.species'),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='enclosure',
            name='building_id',
            field=models.ForeignKey(db_column='Building_ID', on_delete=django.db.models.deletion.CASCADE, to='myapp.building'),
        ),
        migrations.AddField(
            model_name='animal',
            name='enclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.enclosure'),
        ),
        migrations.AddField(
            model_name='participatesin',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_species', to='myapp.species'),
        ),
        migrations.AddField(
            model_name='participatesin',
            name='revenue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_entries', to='myapp.revenuetypes'),
        ),
        migrations.AddField(
            model_name='concession',
            name='revenue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concession_entries', to='myapp.revenuetypes'),
        ),
        migrations.AddField(
            model_name='animalshow',
            name='revenue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_shows', to='myapp.revenuetypes'),
        ),
        migrations.AddField(
            model_name='veterinariancaresfor',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_care_species', to='myapp.species'),
        ),
    ]
